"""empty message

Revision ID: aa278c31d6bd
Revises: 375ff44ed8c7
Create Date: 2025-07-16 22:25:53.932020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa278c31d6bd'
down_revision = '375ff44ed8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    # ### end Alembic commands ###
